media:
  input: "images"
  output: "/images"

content:
  # This acts as a direct, top-level collection link in your sidebar
  - name: reviews
    label: Game Reviews
    type: collection
    path: "content/reviews"
    subfolders: true # Allows creating directories dynamically inside the app
    format: md
    fields:
      - name: title
        label: Game Title
        type: string
      - name: publisher
        label: Publisher
        type: string
      - name: body
        label: Review Content
        type: rich-text
