media:
  input: "images"
  output: "/images"

components:
  curate:
    type: object
    label: Curate
    fields:
      - name: reviewDate
        type: date
      - name: nostalgia
        type: number
      - name: replayability
        type: number
      - name: quality
        type: number
      - name: enjoyability
        type: number
      - name: decision
        type: select
        options:
          values: ["Undecided", "Keep", "Sell"]
      - name: reason
        type: string

content:
  - label: Pages
    path: "content"
    name: content
    type: collection
    subfolders: true
    fields:
      - name: title
        type: string
      - name: zxdbId
        type: number
      - name: publisher
        type: string
      - name: authors
        type: string
      - name: format
        type: string
      - name: genre
        type: string
      - name: tags
        type: string
        list: true
      - name: summary
        type: string
      - name: curation
        component: curate
        label: Curation
      - name: body
        type: rich-text
